import * as mongoose from 'mongoose';
import { Document } from 'mongoose';
export declare const EntitySchema: mongoose.Schema<any, mongoose.Model<any, any, any, any, any, any>, {}, {}, {}, {}, {
    collection: string;
    timestamps: true;
}, {
    key: string;
    status: "error" | "connected" | "pending";
    connectionScope: "user" | "agent";
    serverUrl: string;
    serverUrlHash: string;
    organizationId?: string;
    error?: string;
    createdBy?: string;
    agentId?: string;
    updatedBy?: string;
    label?: string;
    state?: string;
    expiresAt?: NativeDate;
    scope?: string;
    redirectUrl?: string;
    authorizationUrl?: string;
    clientInformation?: string;
    tokens?: string;
    codeVerifier?: string;
    discoveryState?: string;
    authenticatedAt?: NativeDate;
    oauthUserId?: string;
    clientMetadata?: any;
} & mongoose.DefaultTimestampProps, mongoose.Document<unknown, {}, mongoose.FlatRecord<{
    key: string;
    status: "error" | "connected" | "pending";
    connectionScope: "user" | "agent";
    serverUrl: string;
    serverUrlHash: string;
    organizationId?: string;
    error?: string;
    createdBy?: string;
    agentId?: string;
    updatedBy?: string;
    label?: string;
    state?: string;
    expiresAt?: NativeDate;
    scope?: string;
    redirectUrl?: string;
    authorizationUrl?: string;
    clientInformation?: string;
    tokens?: string;
    codeVerifier?: string;
    discoveryState?: string;
    authenticatedAt?: NativeDate;
    oauthUserId?: string;
    clientMetadata?: any;
} & mongoose.DefaultTimestampProps>, {}, mongoose.MergeType<mongoose.DefaultSchemaOptions, {
    collection: string;
    timestamps: true;
}>> & mongoose.FlatRecord<{
    key: string;
    status: "error" | "connected" | "pending";
    connectionScope: "user" | "agent";
    serverUrl: string;
    serverUrlHash: string;
    organizationId?: string;
    error?: string;
    createdBy?: string;
    agentId?: string;
    updatedBy?: string;
    label?: string;
    state?: string;
    expiresAt?: NativeDate;
    scope?: string;
    redirectUrl?: string;
    authorizationUrl?: string;
    clientInformation?: string;
    tokens?: string;
    codeVerifier?: string;
    discoveryState?: string;
    authenticatedAt?: NativeDate;
    oauthUserId?: string;
    clientMetadata?: any;
} & mongoose.DefaultTimestampProps> & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}>;
export declare class CanvasMcpOAuthConnectionEntity extends Document {
    key: string;
    organizationId?: string;
    agentId?: string;
    connectionScope?: 'agent' | 'user';
    oauthUserId?: string;
    serverUrl: string;
    serverUrlHash: string;
    label?: string;
    scope?: string;
    redirectUrl?: string;
    state?: string;
    authorizationUrl?: string;
    status: 'pending' | 'connected' | 'error';
    error?: string;
    clientMetadata?: Record<string, any>;
    clientInformation?: string;
    tokens?: string;
    codeVerifier?: string;
    discoveryState?: string;
    expiresAt?: Date;
    authenticatedAt?: Date;
    createdBy?: string;
    updatedBy?: string;
    createdAt: Date;
    updatedAt: Date;
}
