import { Connection } from 'mongoose';
export declare const connectProviders: {
    provide: string;
    useFactory: (connection: Connection) => import("mongoose").Model<{
        key: string;
        status: "error" | "connected" | "pending";
        connectionScope: "user" | "agent";
        serverUrl: string;
        serverUrlHash: string;
        organizationId?: string;
        error?: string;
        createdBy?: string;
        agentId?: string;
        updatedBy?: string;
        label?: string;
        state?: string;
        expiresAt?: NativeDate;
        scope?: string;
        redirectUrl?: string;
        authorizationUrl?: string;
        clientInformation?: string;
        tokens?: string;
        codeVerifier?: string;
        discoveryState?: string;
        authenticatedAt?: NativeDate;
        oauthUserId?: string;
        clientMetadata?: any;
    } & import("mongoose").DefaultTimestampProps, {}, {}, {}, import("mongoose").Document<unknown, {}, {
        key: string;
        status: "error" | "connected" | "pending";
        connectionScope: "user" | "agent";
        serverUrl: string;
        serverUrlHash: string;
        organizationId?: string;
        error?: string;
        createdBy?: string;
        agentId?: string;
        updatedBy?: string;
        label?: string;
        state?: string;
        expiresAt?: NativeDate;
        scope?: string;
        redirectUrl?: string;
        authorizationUrl?: string;
        clientInformation?: string;
        tokens?: string;
        codeVerifier?: string;
        discoveryState?: string;
        authenticatedAt?: NativeDate;
        oauthUserId?: string;
        clientMetadata?: any;
    } & import("mongoose").DefaultTimestampProps, {}, {}> & {
        key: string;
        status: "error" | "connected" | "pending";
        connectionScope: "user" | "agent";
        serverUrl: string;
        serverUrlHash: string;
        organizationId?: string;
        error?: string;
        createdBy?: string;
        agentId?: string;
        updatedBy?: string;
        label?: string;
        state?: string;
        expiresAt?: NativeDate;
        scope?: string;
        redirectUrl?: string;
        authorizationUrl?: string;
        clientInformation?: string;
        tokens?: string;
        codeVerifier?: string;
        discoveryState?: string;
        authenticatedAt?: NativeDate;
        oauthUserId?: string;
        clientMetadata?: any;
    } & import("mongoose").DefaultTimestampProps & {
        _id: import("mongoose").Types.ObjectId;
    } & {
        __v: number;
    }, import("mongoose").Schema<any, import("mongoose").Model<any, any, any, any, any, any>, {}, {}, {}, {}, {
        collection: string;
        timestamps: true;
    }, {
        key: string;
        status: "error" | "connected" | "pending";
        connectionScope: "user" | "agent";
        serverUrl: string;
        serverUrlHash: string;
        organizationId?: string;
        error?: string;
        createdBy?: string;
        agentId?: string;
        updatedBy?: string;
        label?: string;
        state?: string;
        expiresAt?: NativeDate;
        scope?: string;
        redirectUrl?: string;
        authorizationUrl?: string;
        clientInformation?: string;
        tokens?: string;
        codeVerifier?: string;
        discoveryState?: string;
        authenticatedAt?: NativeDate;
        oauthUserId?: string;
        clientMetadata?: any;
    } & import("mongoose").DefaultTimestampProps, import("mongoose").Document<unknown, {}, import("mongoose").FlatRecord<{
        key: string;
        status: "error" | "connected" | "pending";
        connectionScope: "user" | "agent";
        serverUrl: string;
        serverUrlHash: string;
        organizationId?: string;
        error?: string;
        createdBy?: string;
        agentId?: string;
        updatedBy?: string;
        label?: string;
        state?: string;
        expiresAt?: NativeDate;
        scope?: string;
        redirectUrl?: string;
        authorizationUrl?: string;
        clientInformation?: string;
        tokens?: string;
        codeVerifier?: string;
        discoveryState?: string;
        authenticatedAt?: NativeDate;
        oauthUserId?: string;
        clientMetadata?: any;
    } & import("mongoose").DefaultTimestampProps>, {}, import("mongoose").MergeType<import("mongoose").DefaultSchemaOptions, {
        collection: string;
        timestamps: true;
    }>> & import("mongoose").FlatRecord<{
        key: string;
        status: "error" | "connected" | "pending";
        connectionScope: "user" | "agent";
        serverUrl: string;
        serverUrlHash: string;
        organizationId?: string;
        error?: string;
        createdBy?: string;
        agentId?: string;
        updatedBy?: string;
        label?: string;
        state?: string;
        expiresAt?: NativeDate;
        scope?: string;
        redirectUrl?: string;
        authorizationUrl?: string;
        clientInformation?: string;
        tokens?: string;
        codeVerifier?: string;
        discoveryState?: string;
        authenticatedAt?: NativeDate;
        oauthUserId?: string;
        clientMetadata?: any;
    } & import("mongoose").DefaultTimestampProps> & {
        _id: import("mongoose").Types.ObjectId;
    } & {
        __v: number;
    }>>;
    inject: string[];
}[];
