import { OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Model } from 'mongoose';
import { CanvasFlowDocumentEntity } from './documents-schema';
export type CanvasDocumentScope = {
    organizationId?: string;
    agentId?: string;
    flowId?: string;
    conversationId?: string;
};
export type CanvasArtifactFormat = 'txt' | 'md' | 'csv' | 'json' | 'html' | 'docx' | 'xlsx' | 'pdf';
export type CanvasDocxEdit = {
    type: 'append_table_column';
    tableIndex?: number;
    allTables?: boolean;
    header?: string;
    value?: string;
    values?: any[];
} | {
    type: 'append_paragraph';
    text?: string;
};
export type CanvasXlsxEdit = {
    type: 'set_cell';
    sheet?: string;
    sheetIndex?: number;
    cell?: string;
    value?: any;
    numberFormat?: string;
    valueType?: 'text' | 'number' | 'duration';
} | {
    type: 'append_column';
    sheet?: string;
    sheetIndex?: number;
    header?: string;
    headerRow?: number;
    startRow?: number;
    values?: any[];
    valuesByKey?: Record<string, any>;
    keyColumn?: string | number;
    numberFormat?: string;
    valueType?: 'text' | 'number' | 'duration';
};
export declare class DocumentsService implements OnModuleInit {
    private readonly model;
    private readonly configService;
    private s3Client?;
    constructor(model: Model<CanvasFlowDocumentEntity>, configService: ConfigService);
    onModuleInit(): void;
    private storageMode;
    private s3Bucket;
    private s3Region;
    private getS3Client;
    private localBaseDir;
    private publicApiUrl;
    private safeSegment;
    private fileKey;
    private resolveLocalPath;
    private writeBytes;
    private streamToBuffer;
    private toPlain;
    private contentTypeFor;
    private getReplacementValue;
    private assertArtifactFormat;
    private fillTextTemplate;
    private unwrapGeneratedDocumentContent;
    private extractLooseJsonStringField;
    private flattenReplacements;
    private inlineText;
    private normalizedText;
    private markdownTableCells;
    private isMarkdownTableSeparator;
    private parseRichDocumentContent;
    private renderDocxHeading;
    private renderDocxParagraph;
    private renderDocxLabel;
    private renderDocxListItem;
    private renderDocxCodeBlock;
    private renderDocxTable;
    private renderNewDocx;
    private escapeXml;
    private wordParagraphXml;
    private wordTableCellXml;
    private appendDocxTableColumn;
    private appendDocxParagraph;
    private applyDocxEdits;
    private hasDocxPlaceholders;
    private renderTemplateDocx;
    private parseDelimitedLine;
    private parseDelimitedRows;
    private rowsFromJsonContent;
    private structuredRowsForContent;
    private xlsxCellBorder;
    private normalizeXlsxRows;
    private writeXlsxTable;
    private writeXlsxMergedRow;
    private autosizeXlsxColumns;
    private renderXlsx;
    private xlsxWorksheet;
    private xlsxDurationValue;
    private xlsxCellValue;
    private setXlsxCellValue;
    private xlsxColumnNumber;
    private applyXlsxEdits;
    private renderTemplateXlsx;
    private csvEscape;
    private renderCsv;
    private escapeHtml;
    private renderHtml;
    private pdfInlineText;
    private pdfAvailableWidth;
    private ensurePdfSpace;
    private renderPdfHeading;
    private renderPdfParagraph;
    private renderPdfLabel;
    private renderPdfListItem;
    private renderPdfCodeBlock;
    private renderPdfTable;
    private drawPdfPageDecoration;
    private renderPdf;
    private renderArtifact;
    storeOriginal(params: {
        buffer: Buffer;
        filename: string;
        mimeType?: string;
        scope?: CanvasDocumentScope;
        source?: 'upload' | 'url';
        text?: string;
        structure?: Record<string, any>;
        metadata?: Record<string, any>;
    }): Promise<any>;
    updateExtraction(documentId: string, extraction: {
        text?: string;
        structure?: Record<string, any>;
        metadata?: Record<string, any>;
    }): Promise<any>;
    createArtifact(params: {
        format: CanvasArtifactFormat;
        filename?: string;
        content?: string;
        replacements?: Record<string, any>;
        templateDocumentId?: string;
        docxEdits?: CanvasDocxEdit[];
        xlsxEdits?: CanvasXlsxEdit[];
        parentDocumentId?: string;
        scope?: CanvasDocumentScope;
        metadata?: Record<string, any>;
    }): Promise<any>;
    getRecord(documentId: string, scope?: CanvasDocumentScope): Promise<any>;
    getFile(documentId: string, scope?: CanvasDocumentScope): Promise<{
        record: any;
        buffer: Buffer<any>;
    }>;
    openLocalReadStream(documentId: string, scope?: CanvasDocumentScope): Promise<{
        record: any;
        stream: import("fs").ReadStream;
    }>;
    withSignedDownloadUrl(record: any): Promise<any>;
    getDownloadInfo(documentId: string, scope?: CanvasDocumentScope): Promise<any>;
    list(scope?: CanvasDocumentScope, limit?: number): Promise<{
        documents: any[];
        total: number;
    }>;
}
